import { Geist, Geist_Mono, Road_Rage, Roboto } from "next/font/google";
import "./globals.css";

const roboto = Roboto({
  // variable: "--font-roboto",
  weight: ["300"],
  subsets: ["latin", "math"],
});

export const metadata = {
  title: "Interractive card",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={` ${roboto.className}  `}>{children}</body>
    </html>
  );
}
